version: "3.9"
services:
  cerebro:
    depends_on:
      - redis
    build:
      context: .
    environment:
      ORCA_NAME: cerebro
    volumes:
      - .:/src
      - ./tmp:/tmp
    networks:
      - app-network
  task-server:
    depends_on:
      - redis
      - cerebro
    build:
      context: .
    environment:
      ORCA_NAME: task-server
    volumes:
      - .:/src
      - ./docker-data/tmp:/tmp
    networks:
      - app-network
  redis:
    # keydb is a drop in for redis
    image: eqalpha/keydb
    ports:
      - 6379:6379
    volumes:
      - ./docker-data/redis:/data
    networks:
      - app-network
networks:
  app-network:
