version: "3.9"
services:
  cerebro:
    depends_on:
      - redis
    command: ["sh", "./starter.sh", "cerebro/__init__.py"]
    build:
      context: .
      dockerfile: ./cerebro/Dockerfile
    environment:
      ORCA_NAME: cerebro
    volumes:
      - .:/src
      - ./tmp:/tmp
    networks:
      - app-network
  task-server-a:
    depends_on:
      - redis
      - cerebro
    command: ["sh", "./starter.sh", "task_server_a/__init__.py"]
    build:
      context: .
      dockerfile: ./task_server_a/Dockerfile
    environment:
      ORCA_NAME: task-server-a-test
    volumes:
      - .:/src
      - ./docker-data/tmp:/tmp
    networks:
      - app-network
  task-server-b:
    depends_on:
      - redis
      - cerebro
    command: ["sh", "./starter.sh", "task_server_a/__init__.py"]
    build:
      context: .
      dockerfile: ./task_server_b/Dockerfile
    environment:
      ORCA_NAME: task-server-b-test
    volumes:
      - .:/src
      - ./docker-data/tmp:/tmp
    networks:
      - app-network
  redis:
    # keydb is a drop in for redis
    image: eqalpha/keydb
    ports:
      - 6379:6379
    volumes:
      - ./docker-data/redis:/data
    networks:
      - app-network
networks:
  app-network:
