version: "3.9"
services:
  cerebro:
    depends_on:
      - redis
    command: ["sh", "./starter.sh", "cerebro/__init__.py"]
    build:
      context: .
      dockerfile: ./cerebro/Dockerfile
    environment:
      ORCA_NAME: cerebro
    volumes:
      - .:/src
      - ./tmp:/tmp
    networks:
      - app-network
  task-server-letters:
    depends_on:
      - redis
      - cerebro
    command:
      ["sh", "./starter.sh", "task_servers/task_server_letters/__init__.py"]
    build:
      context: .
      dockerfile: ./task_servers/Dockerfile
    environment:
      ORCA_NAME: task-server-letters
    volumes:
      - .:/src
      - ./docker-data/tmp:/tmp
    networks:
      - app-network
  task-server-nums:
    depends_on:
      - redis
      - cerebro
    command: ["sh", "./starter.sh", "task_servers/task_server_nums/__init__.py"]
    build:
      context: .
      dockerfile: ./task_servers/Dockerfile
    environment:
      ORCA_NAME: task-server-nums
    volumes:
      - .:/src
      - ./docker-data/tmp:/tmp
    networks:
      - app-network
  redis:
    # keydb is a drop in for redis
    image: eqalpha/keydb
    ports:
      - 6379:6379
    volumes:
      - ./docker-data/redis:/data
    networks:
      - app-network
networks:
  app-network:
